name: build

on:
  push:
    branches: [ unstable ]
  pull_request:
    branches: [ unstable ]

jobs:
  build:

    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    container: 
      image: materialstheory/solid_dmft_ci

    steps:
      - uses: actions/checkout@v2
        with: 
          path: 'solid_dmft.src'

      - name: Build solid_dmft
        run: |
          mkdir solid_dmft.build && cd solid_dmft.build && cmake ../solid_dmft.src -DBuild_Documentation=ON -DMPIEXEC_PREFLAGS='--allow-run-as-root' 
          make

      - name: Test solid_dmft
        run: |
          cd solid_dmft.build
          ctest --output-on-failure

      - name: checkout github pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: 'gh-pages'

      - name: copy documentation files
        run: rsync -av solid_dmft.build/doc/html/ gh-pages/

      - name: commit changes to gh-pages branch
        run: |
          cd gh-pages/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f .
          git commit -m "generated doc"
          git push origin gh-pages


